#!/usr/bin/env python3

import subprocess
import sys
import os

def remove_entry(name):
  subprocess.check_call(["ssh-keygen", "-f", known_hosts, "-R", name])

known_hosts = os.path.expanduser("~/.ssh/known_hosts")
user_and_hostname = sys.argv[1]
hostname = user_and_hostname.split('@', 1)[-1]
ip_address = subprocess.check_output(["dig", "+short", hostname]).decode('utf-8').rstrip()
remove_entry(hostname)
remove_entry(ip_address)

new_hosts = subprocess.check_output(["ssh-keyscan", "-H", hostname]).decode('utf-8')
with open(known_hosts, 'a') as f:
  f.write(new_hosts)

exit_code = subprocess.call(['ssh'] + sys.argv[1:])
sys.exit(exit_code)
